# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'TheMovieDB' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for TheMovieDB
    pod 'Alamofire', '~> 4.7.3'
    pod 'UIColor_Hex_Swift', '~> 4.2.0'
    pod 'Kingfisher', '~> 4.8.1'
    pod 'FontAwesome.swift', '~> 1.4.5'
    
    target 'TheMovieDBTests' do
        inherit! :search_paths
        # Pods for testing
    end
    
    target 'TheMovieDBUITests' do
        inherit! :search_paths
        # Pods for testing
    end
    
end
